# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0002_auto_20200111_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 10, 31, 39, 507464)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 10, 31, 39, 506849)),
        ),
    ]
