# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0003_auto_20200112_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default=datetime.datetime(2020, 1, 12, 15, 59, 27, 770661, tzinfo=utc), upload_to='home/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2020, 1, 12, 15, 59, 47, 340159, tzinfo=utc), upload_to='home/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 18, 59, 13, 974842)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 18, 59, 13, 974084)),
        ),
    ]
