# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-13 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0005_auto_20200113_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 17, 8, 31, 887575)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 17, 8, 31, 886070)),
        ),
    ]
